# Site settings
title: Exercise: Simply Social
description: Front end exercise for Invision

# Build settings
markdown: kramdown
permalink: /:title
destination: _deploy

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "My Author" # Set default author name
      categories: "cats"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
